create table bookmarks (
  id INTEGER primary key generated by default as identity,
  name text not null,
  url text not null,
  description text,
  rating INTEGER not null
);

ALTER TABLE bookmarks 
   ADD CONSTRAINT rating_range 
   CHECK (rating > 0 AND rating < 6);